<a href="https://colab.research.google.com/github/Aravind-6646/Data-Analytics-and-Visualization/blob/main/Nifty_next_50.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pandas as pd
df=pd.read_csv(r"/content/ind_niftynext50list.csv")
df

,Company Name,Industry,Symbol,Series,ISIN Code
0,ABB India Ltd.,Capital Goods,ABB,EQ,INE117A01022
1,Adani Energy Solutions Ltd.,Power,ADANIENSOL,EQ,INE931S01010
2,Adani Green Energy Ltd.,Power,ADANIGREEN,EQ,INE364U01010
3,Adani Power Ltd.,Power,ADANIPOWER,EQ,INE814H01029
4,Ambuja Cements Ltd.,Construction Materials,AMBUJACEM,EQ,INE079A01024
5,Avenue Supermarts Ltd.,Consumer Services,DMART,EQ,INE192R01011
6,Bajaj Holdings & Investment Ltd.,Financial Services,BAJAJHLDNG,EQ,INE118A01012
7,Bank of Baroda,Financial Services,BANKBARODA,EQ,INE028A01039
8,Bharat Petroleum Corporation Ltd.,Oil Gas & Consumable Fuels,BPCL,EQ,INE029A01011
9,Bosch Ltd.,Automobile and Auto Components,BOSCHLTD,EQ,INE323A01026
10,Britannia Industries Ltd.,Fast Moving Consumer Goods,BRITANNIA,EQ,INE216A01030
11,CG Power and Industrial Solutions Ltd.,Capital Goods,CGPOWER,EQ,INE067A01029
12,Canara Bank,Financial Services,CANBK,EQ,INE476A01022
13,Cholamandalam Investment and Finance Company Ltd.,Financial Services,CHOLAFIN,EQ,INE121A01024
14,Cummins India Ltd.,Capital Goods,CUMMINSIND,EQ,INE298A01020
15,DLF Ltd.,Realty,DLF,EQ,INE271C01023
16,Divi's Laboratories Ltd.,Healthcare,DIVISLAB,EQ,INE361B01024
17,GAIL (India) Ltd.,Oil Gas & Consumable Fuels,GAIL,EQ,INE129A01019
18,Godrej Consumer Products Ltd.,Fast Moving Consumer Goods,GODREJCP,EQ,INE102D01028
19,HDFC Asset Management Company Ltd.,Financial Services,HDFCAMC,EQ,INE127D01025
20,Hindustan Aeronautics Ltd.,Capital Goods,HAL,EQ,INE066F01020
21,Hindustan Zinc Ltd.,Metals & Mining,HINDZINC,EQ,INE267A01025
22,Hyundai Motor India Ltd.,Automobile and Auto Components,HYUNDAI,EQ,INE0V6F01027
23,Indian Hotels Co. Ltd.,Consumer Services,INDHOTEL,EQ,INE053A01029
24,Indian Oil Corporation Ltd.,Oil Gas & Consumable Fuels,IOC,EQ,INE242A01010
25,Indian Railway Finance Corporation Ltd.,Financial Services,IRFC,EQ,INE053F01010
26,Jindal Steel Ltd.,Metals & Mining,JINDALSTEL,EQ,INE749A01030
27,LTM Ltd.,Information Technology,LTM,EQ,INE214T01019
28,Lodha Developers Ltd.,Realty,LODHA,EQ,INE670K01029
29,Mazagoan Dock Shipbuilders Ltd.,Capital Goods,MAZDOCK,EQ,INE249Z01020
30,Muthoot Finance Ltd.,Financial Services,MUTHOOTFIN,EQ,INE414G01012
31,Pidilite Industries Ltd.,Chemicals,PIDILITIND,EQ,INE318A01026
32,Power Finance Corporation Ltd.,Financial Services,PFC,EQ,INE134E01011
33,Punjab National Bank,Financial Services,PNB,EQ,INE160A01022
34,REC Ltd.,Financial Services,RECLTD,EQ,INE020B01018
35,Samvardhana Motherson International Ltd.,Automobile and Auto Components,MOTHERSON,EQ,INE775A01035
36,Shree Cement Ltd.,Construction Materials,SHREECEM,EQ,INE070A01015
37,Siemens Energy India Ltd.,Capital Goods,ENRIN,EQ,INE1NPP01017
38,Siemens Ltd.,Capital Goods,SIEMENS,EQ,INE003A01024
39,Solar Industries India Ltd.,Chemicals,SOLARINDS,EQ,INE343H01029
40,TVS Motor Company Ltd.,Automobile and Auto Components,TVSMOTOR,EQ,INE494B01023
41,Tata Capital Ltd.,Financial Services,TATACAP,EQ,INE976I01016
42,Tata Motors Ltd.,Capital Goods,TMCV,EQ,INE1TAE01010
43,Tata Power Co. Ltd.,Power,TATAPOWER,EQ,INE245A01021
44,Torrent Pharmaceuticals Ltd.,Healthcare,TORNTPHARM,EQ,INE685A01028
45,Union Bank of India,Financial Services,UNIONBANK,EQ,INE692A01016
46,United Spirits Ltd.,Fast Moving Consumer Goods,UNITDSPR,EQ,INE854D01024
47,Varun Beverages Ltd.,Fast Moving Consumer Goods,VBL,EQ,INE200M01039
48,Vedanta Ltd.,Metals & Mining,VEDL,EQ,INE205A01025
49,Zydus Lifesciences Ltd.,Healthcare,ZYDUSLIFE,EQ,INE010B01027

In [16]:
df=df[df['Industry']=='Financial Services']
df

,Company Name,Industry,Symbol,Series,ISIN Code
6,Bajaj Holdings & Investment Ltd.,Financial Services,BAJAJHLDNG,EQ,INE118A01012
7,Bank of Baroda,Financial Services,BANKBARODA,EQ,INE028A01039
12,Canara Bank,Financial Services,CANBK,EQ,INE476A01022
13,Cholamandalam Investment and Finance Company Ltd.,Financial Services,CHOLAFIN,EQ,INE121A01024
19,HDFC Asset Management Company Ltd.,Financial Services,HDFCAMC,EQ,INE127D01025
25,Indian Railway Finance Corporation Ltd.,Financial Services,IRFC,EQ,INE053F01010
30,Muthoot Finance Ltd.,Financial Services,MUTHOOTFIN,EQ,INE414G01012
32,Power Finance Corporation Ltd.,Financial Services,PFC,EQ,INE134E01011
33,Punjab National Bank,Financial Services,PNB,EQ,INE160A01022
34,REC Ltd.,Financial Services,RECLTD,EQ,INE020B01018
41,Tata Capital Ltd.,Financial Services,TATACAP,EQ,INE976I01016
45,Union Bank of India,Financial Services,UNIONBANK,EQ,INE692A01016

In [19]:
df=df[df['Industry']=='Construction Materials']
df

,Company Name,Industry,Symbol,Series,ISIN Code
4,Ambuja Cements Ltd.,Construction Materials,AMBUJACEM,EQ,INE079A01024
36,Shree Cement Ltd.,Construction Materials,SHREECEM,EQ,INE070A01015

In [21]:
df=df[df['Industry']=='Metals & Mining']
df

           Company Name         Industry      Symbol Series     ISIN Code
21  Hindustan Zinc Ltd.  Metals & Mining    HINDZINC     EQ  INE267A01025
26    Jindal Steel Ltd.  Metals & Mining  JINDALSTEL     EQ  INE749A01030
48         Vedanta Ltd.  Metals & Mining        VEDL     EQ  INE205A01025